# This will just label all PRs every 5 minutes
name: "Pull Request Labeler"
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: paulfantom/periodic-labeler@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          LABEL_MAPPINGS_FILE: .github/labeler.yml

# This version doesn't work for PRs from forks (see https://github.com/actions/labeler/issues/12)
# on: 
# - pull_request

# jobs:
#   triage:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/labeler@v2
#       with:
#         repo-token: "${{ secrets.GITHUB_TOKEN }}"
